import React from "react"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <React.Fragment>
      {children}
    </React.Fragment>
  )
}
