import React, { Suspense } from "react"
import Loading from "../components/loading"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (

    <React.Fragment>
      <Suspense fallback={<Loading></Loading>}>

      {children}
      </Suspense>
    </React.Fragment>
  )
}
