import { ProvideSocketIoClient } from "../providers/SocketIoProvider"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (

    <html lang="en">
      {/* <ProvideSocketIoClient> */}
        <body>{children}</body>
      {/* </ProvideSocketIoClient> */}
    </html>
  )
}
