import React from "react"
import { getSession } from "../actions/auth"
import { ProvideSocketIoClient } from "../providers/SocketIoProvider"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (

    <React.Fragment>
      {children}
    </React.Fragment>
  )
}
